/*
 * 2020 Federal Taxes - Married filing jointly 
 * Midterm Project - Advanced Java
 * Written by Jennifer Casto
 */
package federaltaxcalculator2021;

import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.text.NumberFormat;

public class MarriedFilingJointly extends javax.swing.JFrame {

    /**
     * Creates new form MarriedFilingJointly
     */
    public MarriedFilingJointly() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lNameField = new javax.swing.JTextField();
        lblIncome = new javax.swing.JLabel();
        IncomeField = new javax.swing.JTextField();
        btnEstimateTax = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblErrorFN = new javax.swing.JLabel();
        lblErrorLN = new javax.swing.JLabel();
        lblErrorI = new javax.swing.JLabel();
        lblTaxStatement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");

        lblIncome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIncome.setText("Annual Income");

        btnEstimateTax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEstimateTax.setText("Estimate Tax");
        btnEstimateTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstimateTaxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Taxable Income");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Married filing jointly");

        lblResults.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTaxStatement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTaxStatement.setText("Tax Statement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(lblTaxStatement)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName)
                                        .addGap(85, 85, 85)
                                        .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblLastName)
                                                .addGap(171, 171, 171))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIncome)
                                                .addGap(58, 58, 58)
                                                .addComponent(IncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnReset)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEstimateTax)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrorFN)
                                            .addComponent(lblErrorLN)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(lblErrorI)))
                        .addGap(18, 18, 18)
                        .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTaxStatement))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblErrorLN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName)
                                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblErrorFN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lblLastName))
                                            .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIncome))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEstimateTax)
                                    .addComponent(btnReset))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblErrorI)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        lblResults.getAccessibleContext().setAccessibleName("lblResult");

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Estimate my tax Button pressed
    private void btnEstimateTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstimateTaxActionPerformed
    // Declare Variables
    // Retrieve input from user
        String FName = fNameField.getText();
        String LName = lNameField.getText();
        String txtIncome = IncomeField.getText();
        
    //  Variable to hold numerical converted value
        double Income = 0;
        
    // boolean used for error checking
        Boolean isValid = false;
        
    // Check input for Blank Entries
    while (!isValid){
        
        //First name Check    
        int FNameLength = FName.length();
        if (FNameLength <=0){
            lblErrorFN.setText("* First Name is Required");
            isValid = false;
        }
        else
        {
            isValid = true;
        }
        
        // Last name check
        int LNameLength = FName.length();
        if (LNameLength <=0){
            lblErrorLN.setText("* Last Name is Required");
            isValid = false;
        }
        else
        {
            isValid = true;
        }
        
        // Postitive income Check
        Income = Double.parseDouble(txtIncome);
        if (Income < 0){        
            lblErrorI.setText("Income is Required");
            isValid = false;
        }
        else
        {
            isValid = true;
        }
    }
   
if (isValid){
LocalDateTime now = LocalDateTime.now();
DateTimeFormatter format = DateTimeFormatter.ofPattern("MM-dd-yy HH.mm");
String dateTime =  now.format(format);
NumberFormat formatter = NumberFormat.getCurrencyInstance();

FederalTaxCalculator2021 Estimate = new FederalTaxCalculator2021(FName,LName,Income);


lblResults.setText("<html><body>Good "/*greeting*/+Estimate.getFName()+" " + Estimate.getLName() +
        "<br>This is your Income Tax Statement printed today:" +dateTime+
        "<br>This tax statement is for income earned during the 2021 year" +
        "<br>Calculated at Married Filing jointly rates"+
        "<br>Your Taxable income is: "+Estimate.getIncome()+
        "<br>The federal income tax on your taxable income is: "+formatter.format(Estimate.getTaxEstimate())+
        "<br>Thank you for allowing us to calculate you federal tax"+
        "<br>We would appreciate if your let us file your tax return.</body></html>"       
        
        );
}}
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarriedFilingJointly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarriedFilingJointly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarriedFilingJointly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarriedFilingJointly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarriedFilingJointly().setVisible(true);
            }
        });    
    }//GEN-LAST:event_btnEstimateTaxActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        fNameField.setText("");
        lNameField.setText("");
        IncomeField.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IncomeField;
    private javax.swing.JButton btnEstimateTax;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField fNameField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lNameField;
    private javax.swing.JLabel lblErrorFN;
    private javax.swing.JLabel lblErrorI;
    private javax.swing.JLabel lblErrorLN;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblTaxStatement;
    // End of variables declaration//GEN-END:variables
}  
